# Generated by Django 4.0.7 on 2022-08-28 16:10

import core.image_validator
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_category', 'Mövcud kateqoriyalara baxa bilər'), ('add_category', 'Kateqoriya əlavə edə bilər'), ('change_category', 'Kateqoriya məlumatlarını yeniləyə bilər'), ('delete_category', 'Kateqoriya silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_unitofmeasure', 'Mövcud ölçü vahidlərinə baxa bilər'), ('add_unitofmeasure', 'Ölçü vahidi əlavə edə bilər'), ('change_unitofmeasure', 'Ölçü vahidi məlumatlarını yeniləyə bilər'), ('delete_unitofmeasure', 'Ölçü vahidini silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='media/product/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('is_gift', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company')),
                ('unit_of_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unitofmeasure')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_product', 'Mövcud məhsullara baxa bilər'), ('add_product', 'Məhsul əlavə edə bilər'), ('change_product', 'Məhsul məlumatlarını yeniləyə bilər'), ('delete_product', 'Məhsul silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
