# Generated by Django 3.2.12 on 2022-08-26 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferFromOfficeToCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company_cashbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_office_to_company', to='cashbox.companycashbox')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('office_cashbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_office_to_company', to='cashbox.officecashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_transferfromofficetocompany', 'Mövcud officedən şirkətə olan transferlərə baxa bilər'), ('add_transferfromofficetocompany', 'Officedən şirkətə transfer edə bilər'), ('change_transferfromofficetocompany', 'Officedən şirkətə olan transfer məlumatlarını yeniləyə bilər'), ('delete_transferfromofficetocompany', 'Officedən şirkətə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TransferFromHoldingToCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company_cashbox', models.ManyToManyField(related_name='transfer_from_holding_to_company', to='cashbox.CompanyCashbox')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('holding_cashbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_holding_to_company', to='cashbox.holdingcashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_transferfromholdingtocompany', 'Mövcud holdinqdən şirkətlərə olan transferlərə baxa bilər'), ('add_transferfromholdingtocompany', 'Holdinqdən şirkətlərə transfer edə bilər'), ('change_transferfromholdingtocompany', 'Holdinqdən şirkətlərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_transferfromholdingtocompany', 'Holdinqdən şirkətlərə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TransferFromCompanyToOffices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company_cashbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_company_to_offices', to='cashbox.companycashbox')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('office_cashbox', models.ManyToManyField(related_name='transfer_from_company_to_offices', to='cashbox.OfficeCashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_transferfromcompanytooffices', 'Mövcud şirkətdən officelərə olan transferlərə baxa bilər'), ('add_transferfromcompanytooffices', 'Şirkətdən officelərə transfer edə bilər'), ('change_transferfromcompanytooffices', 'Şirkətdən officelərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_transferfromcompanytooffices', 'Şirkətdən officelərə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='TransferFromCompanyToHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.FloatField(default=0)),
                ('transfer_date', models.DateField(auto_now=True)),
                ('transfer_note', models.TextField(blank=True, null=True)),
                ('remaining_amount', models.FloatField(blank=True, default=0)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company_cashbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_company_to_holding', to='cashbox.companycashbox')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('holding_cashbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from_company_to_holding', to='cashbox.holdingcashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_transferfromcompanytoholding', 'Mövcud şirkətdən holdinqlərə olan transferlərə baxa bilər'), ('add_transferfromcompanytoholding', 'Şirkətdən holdinqlərə transfer edə bilər'), ('change_transferfromcompanytoholding', 'Şirkətdən holdinqlərə olan transfer məlumatlarını yeniləyə bilər'), ('delete_transferfromcompanytoholding', 'Şirkətdən holdinqlərə olan transfer məlumatlarını silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
