# Generated by Django 3.2.12 on 2022-08-26 14:11

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import measurement.measures.volume


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('is_gift', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_category', 'Mövcud kateqoriyalara baxa bilər'), ('add_category', 'Kateqoriya əlavə edə bilər'), ('change_category', 'Kateqoriya məlumatlarını yeniləyə bilər'), ('delete_category', 'Kateqoriya silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('price', models.FloatField(default=0)),
                ('volume', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.volume.Volume, null=True)),
                ('weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_product', 'Mövcud məhsullara baxa bilər'), ('add_product', 'Məhsul əlavə edə bilər'), ('change_product', 'Məhsul məlumatlarını yeniləyə bilər'), ('delete_product', 'Məhsul silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
