# Generated by Django 3.2.12 on 2022-08-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_unitofmeasure', 'Mövcud kateqoriyalara baxa bilər'), ('add_unitofmeasure', 'Kateqoriya əlavə edə bilər'), ('change_unitofmeasure', 'Kateqoriya məlumatlarını yeniləyə bilər'), ('delete_unitofmeasure', 'Kateqoriya silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unitofmeasure'),
        ),
    ]
