# Generated by Django 3.2.12 on 2022-08-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220827_0542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_unitofmeasure', 'Mövcud ölçü vahidlərinə baxa bilər'), ('add_unitofmeasure', 'Ölçü vahidi əlavə edə bilər'), ('change_unitofmeasure', 'Ölçü vahidi məlumatlarını yeniləyə bilər'), ('delete_unitofmeasure', 'Ölçü vahidini silə bilər'))},
        ),
    ]
