# Generated by Django 3.2.12 on 2022-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220828_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_gift',
        ),
        migrations.AddField(
            model_name='product',
            name='is_gift',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
