# Generated by Django 3.2.12 on 2022-08-26 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment', models.BooleanField(blank=True, default=False)),
                ('loan_term', models.IntegerField(blank=True, default=0)),
                ('discount', models.FloatField(blank=True, default=0)),
                ('service_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, default=0)),
                ('initial_payment', models.FloatField(blank=True, default=0)),
                ('total_amount_to_be_paid', models.FloatField(blank=True, default=0)),
                ('confirmation', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('is_auto', models.BooleanField(default=False)),
                ('create_date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='contract.contract')),
                ('product', models.ManyToManyField(related_name='services', to='product.Product')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_service', 'Mövcud servislərə baxa bilər'), ('add_service', 'Servis əlavə edə bilər'), ('change_service', 'Servis məlumatlarını yeniləyə bilər'), ('delete_service', 'Servis silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_to_be_paid', models.FloatField(blank=True, default=0)),
                ('amount_to_be_paid', models.FloatField(blank=True, default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_payment', to='services.service')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_servicepayment', 'Mövcud service ödəmələrinə baxa bilər'), ('add_servicepayment', 'Service ödəmə əlavə edə bilər'), ('change_servicepayment', 'Service ödəmə məlumatlarını yeniləyə bilər'), ('delete_servicepayment', 'Service ödəmə silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
