# Generated by Django 3.2.12 on 2022-08-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220828_0343'),
        ('services', '0002_auto_20220828_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProductForContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_period', models.IntegerField(default=1)),
                ('product', models.ManyToManyField(related_name='service_for_contracts', to='product.Product')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_serviceproductforcontract', 'Müqaviləyə periodik servis üçün təyin olunmuş məhsullara baxa bilər'), ('add_serviceproductforcontract', 'Müqaviləyə periodik servis üçün məhsullar əlavə edə bilər'), ('change_serviceproductforcontract', 'Müqaviləyə periodik servis üçün təyin olunmuş məhsulların məlumatlarını yeniləyə bilər'), ('delete_serviceproductforcontract', 'Müqaviləyə periodik servis üçün təyin olunmuş məhsulları silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
