# Generated by Django 3.2.12 on 2022-08-27 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backup_restore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupandrestore',
            name='backup_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupandrestore',
            name='media_backup_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='backupandrestore',
            name='restore_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
