# Generated by Django 3.2.12 on 2022-08-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_restore', '0003_backupandrestore_backup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupandrestore',
            name='backup_type',
        ),
        migrations.AlterField(
            model_name='backupandrestore',
            name='backup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backupandrestore',
            name='media_backup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='backupandrestore',
            name='restore_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
