INSTALLMENT = 'KREDİT'
CASH = 'NƏĞD'

CONTINUING = "DAVAM EDƏN"
FINISHED = "BİTMİŞ"
CANCELLED = "DÜŞƏN"
NONE = "YOXDUR"
NEW_GRAPH = "YENİ QRAFİK"

ODENEN = "ÖDƏNƏN"
ODENMEYEN = "ÖDƏNMƏYƏN"

BURAXILMIS_AY = "BURAXILMIŞ AY"
NATAMAM_AY = "NATAMAM AY"
RAZILASDIRILMIS_AZ_ODEME = "RAZILAŞDIRILMIŞ AZ ÖDƏMƏ"
ARTIQ_ODEME = "ARTIQ ÖDƏMƏ"
SON_AYIN_BOLUNMESI = "SON AYIN BÖLÜNMƏSİ"

GECIKDIRME = "GECİKDİRMƏ"

SIFIR_NOVBETI_AY = "SIFIR NÖVBƏTİ AY"
SIFIR_SONUNCU_AY = "SIFIR SONUNCU AY"
SIFIR_DIGER_AYLAR = "SIFIR DİGƏR AYLAR"

NATAMAM_NOVBETI_AY = "NATAMAM NÖVBƏTİ AY"
NATAMAM_SONUNCU_AY = "NATAMAM SONUNCU AY"
NATAMAM_DIGER_AYLAR = "NATAMAM DİGƏR AYLAR"

ARTIQ_BIR_AY = "ARTIQ BİR AY"
ARTIQ_BUTUN_AYLAR = "ARTIQ BÜTÜN AYLAR"

MODIFIED_PRODUCT = "DƏYİŞİLMİŞ MƏHSUL"

BORCU_BAGLA = "BORCU BAĞLA"

PAYMENT_STYLE_CHOICES = [
    (CASH, "NƏĞD"),
    (INSTALLMENT, "KREDİT")
]

NEW_GRAPH_CHOICES = [
    (NEW_GRAPH, "YENİ QRAFİK")
]

CONTRACT_STATUS_CHOICES = [
    (CONTINUING, "DAVAM EDƏN"),
    (FINISHED, "BİTMİŞ"),
    (CANCELLED, "DÜŞƏN")
]

INITIAL_PAYMENT_STATUS_CHOICES = [
    (NONE, "YOXDUR"),
    (FINISHED, "BİTMİŞ"),
    (CONTINUING, "DAVAM EDƏN"),
]

INITIAL_PAYMENT_DEBT_STATUS_CHOICES = [
    (NONE, "YOXDUR"),
    (FINISHED, "BİTMİŞ"),
    (CONTINUING, "DAVAM EDƏN"),
]

MODIFIED_PRODUCT_STATUS_CHOICES = [
    (MODIFIED_PRODUCT, "DƏYİŞİLMİŞ MƏHSUL")
]

ODEME_STATUS_CHOICES = [
    (ODENMEYEN, "ÖDƏNMƏYƏN"),
    (ODENEN, "ÖDƏNƏN"),
]

SERTLI_ODEME_STATUSU = [
    (BURAXILMIS_AY, "BURAXILMIŞ AY"),
    (NATAMAM_AY, "NATAMAM AY"),
    (RAZILASDIRILMIS_AZ_ODEME, "RAZILAŞDIRILMIŞ AZ ÖDƏMƏ"),
    (ARTIQ_ODEME, "ARTIQ ÖDƏMƏ"),
    (SON_AYIN_BOLUNMESI, "SON AYIN BÖLÜNMƏSİ")
]

GECIKDIRME_STATUS_CHOICES = [
    (GECIKDIRME, "GECİKDİRMƏ")
]

SIFIR_STATUS_CHOICES = [
    (SIFIR_NOVBETI_AY, "SIFIR NÖVBƏTİ AY"),
    (SIFIR_SONUNCU_AY, "SIFIR SONUNCU AY"),
    (SIFIR_DIGER_AYLAR, "SIFIR DİGƏR AYLAR")
]

NATAMAM_STATUS_CHOICES = [
    (NATAMAM_NOVBETI_AY, "NATAMAM NÖVBƏTİ AY"),
    (NATAMAM_SONUNCU_AY, "NATAMAM SONUNCU AY"),
    (NATAMAM_DIGER_AYLAR, "NATAMAM DİGƏR AYLAR")
]

ARTIQ_ODEME_STATUS_CHOICES = [
    (ARTIQ_BIR_AY, "ARTIQ BİR AY"),
    (ARTIQ_BUTUN_AYLAR, "ARTIQ BÜTÜN AYLAR")
]

BORCU_BAGLA_STATUS_CHOICES = [
    (BORCU_BAGLA, "BORCU BAĞLA")
]

ODENIS_USLUBU_CHOICES = [
    (CASH, "NƏĞD"),
    (INSTALLMENT, "KREDİT"),
]
