# Generated by Django 3.2.12 on 2022-08-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='auto_create_warehouse',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
