# Generated by Django 3.2.12 on 2022-08-27 03:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('Standart', 'Standart')], default='Standart', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.region'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date_of_work',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
