# Generated by Django 3.2.12 on 2022-08-29 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220829_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_date_of_work',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
