# Generated by Django 3.2.12 on 2022-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12),
        ),
    ]
