# Generated by Django 3.2.12 on 2022-08-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='manager',
            new_name='supervisor',
        ),
    ]
