# Generated by Django 3.2.12 on 2022-08-27 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'default_permissions': [], 'ordering': ('pk',), 'permissions': (('view_installment', 'Mövcud kredit ödəmələrinə baxa bilər'), ('add_installment', 'Kredit ödəməsi əlavə edə bilər'), ('change_installment', 'Kredit ödəməsi məlumatlarını yeniləyə bilər'), ('delete_installment', 'Kredit ödəməsini silə bilər'))},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='creditor',
        ),
        migrations.AlterField(
            model_name='contract',
            name='compensation_expense',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='compensation_income',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment_debt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ContractCreditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='contract.contract')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_contractcreditor', 'Mövcud müqavilələrin kreditorlarına baxa bilər'), ('add_contractcreditor', 'Müqaviləyə kreditor əlavə edə bilər'), ('change_contractcreditor', 'Müqavilənin kreditor məlumatlarını yeniləyə bilər'), ('delete_contractcreditor', 'Müqavilənin kreditorunu silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
