# Generated by Django 3.2.12 on 2022-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryview',
            name='final_salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
