# Generated by Django 4.0.7 on 2022-08-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupAndRestore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_date', models.DateField(blank=True, null=True)),
                ('restore_date', models.DateField(blank=True, null=True)),
                ('media_backup_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_backupandrestore', 'Mövcud `backup and restore`lara baxa bilər'), ('add_backupandrestore', '`Backup and restore` əlavə edə bilər'), ('change_backupandrestore', '`Backup and restore` məlumatlarını yeniləyə bilər'), ('delete_backupandrestore', '`Backup and restore` silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
