# Generated by Django 4.0.7 on 2022-08-28 16:10

import core.image_validator
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeCashboxIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_office_income', to=settings.AUTH_USER_MODEL)),
                ('office_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_cashbox_income', to='cashbox.officecashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_officecashboxincome', 'Mövcud ofis cashbox mədaxillərə baxa bilər'), ('add_officecashboxincome', 'Office cashbox mədaxil əlavə edə bilər'), ('change_officecashboxincome', 'Office cashbox mədaxil məlumatlarını yeniləyə bilər'), ('delete_officecashboxincome', 'Office cashbox mədaxil silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OfficeCashboxExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('image_of_receipt', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_office_expense', to=settings.AUTH_USER_MODEL)),
                ('office_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_cashbox_expense', to='cashbox.officecashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_officecashboxexpense', 'Mövcud office cashbox məxariclərə baxa bilər'), ('add_officecashboxexpense', 'Office cashbox məxaric əlavə edə bilər'), ('change_officecashboxexpense', 'Office cashbox məxaric məlumatlarını yeniləyə bilər'), ('delete_officecashboxexpense', 'Office cashbox məxaric silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingCashboxIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_income', to=settings.AUTH_USER_MODEL)),
                ('holding_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_cashbox_income', to='cashbox.holdingcashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingcashboxincome', 'Mövcud holdinq cashbox mədaxillərə baxa bilər'), ('add_holdingcashboxincome', 'Holdinq cashbox mədaxil əlavə edə bilər'), ('change_holdingcashboxincome', 'Holdinq cashbox mədaxil məlumatlarını yeniləyə bilər'), ('delete_holdingcashboxincome', 'Holdinq cashbox mədaxil silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='HoldingCashboxExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('image_of_receipt', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_holding_expense', to=settings.AUTH_USER_MODEL)),
                ('holding_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_cashbox_expense', to='cashbox.holdingcashbox')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_holdingcashboxexpense', 'Mövcud holdinq cashbox məxariclərə baxa bilər'), ('add_holdingcashboxexpense', 'Holdinq cashbox məxaric əlavə edə bilər'), ('change_holdingcashboxexpense', 'Holdinq cashbox məxaric məlumatlarını yeniləyə bilər'), ('delete_holdingcashboxexpense', 'Holdinq cashbox məxaric silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CompanyCashboxIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cashbox_income', to='cashbox.companycashbox')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_income', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_companycashboxincome', 'Mövcud şirkət cashbox mədaxillərə baxa bilər'), ('add_companycashboxincome', 'Şirkət cashbox mədaxil əlavə edə bilər'), ('change_companycashboxincome', 'Şirkət cashbox mədaxil məlumatlarını yeniləyə bilər'), ('delete_companycashboxincome', 'Şirkət cashbox mədaxil silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='CompanyCashboxExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('image_of_receipt', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', validators=[core.image_validator.file_size, django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])])),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=None)),
                ('previous_balance', models.FloatField(blank=True, default=0)),
                ('subsequent_balance', models.FloatField(blank=True, default=0)),
                ('company_cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cashbox_expense', to='cashbox.companycashbox')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_expense', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_companycashboxexpense', 'Mövcud şirkət cashbox məxariclərə baxa bilər'), ('add_companycashboxexpense', 'Şirkət cashbox məxaric əlavə edə bilər'), ('change_companycashboxexpense', 'Şirkət cashbox məxaric məlumatlarını yeniləyə bilər'), ('delete_companycashboxexpense', 'Şirkət cashbox məxaric silə bilər')),
                'default_permissions': [],
            },
        ),
    ]
