# Generated by Django 3.2.12 on 2022-08-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0004_auto_20220827_1227'),
        ('income_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officekassaincome',
            options={'default_permissions': [], 'ordering': ('-pk',), 'permissions': (('view_officecashboxincome', 'Mövcud ofis kassa mədaxillərə baxa bilər'), ('add_officecashboxincome', 'Ofis kassa mədaxil əlavə edə bilər'), ('change_officecashboxincome', 'Ofis kassa mədaxil məlumatlarını yeniləyə bilər'), ('delete_officecashboxincome', 'Ofis kassa mədaxil silə bilər'))},
        ),
        migrations.AlterField(
            model_name='companycashboxexpense',
            name='company_cashbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_cashbox_expense', to='cashbox.companycashbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companycashboxincome',
            name='company_cashbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_cashbox_income', to='cashbox.companycashbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holdingcashboxexpense',
            name='holding_cashbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holding_cashbox_expense', to='cashbox.holdingcashbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holdingcashboxincome',
            name='holding_cashbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holding_cashbox_income', to='cashbox.holdingcashbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officekassaexpense',
            name='office_cashbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='office_cashbox_expense', to='cashbox.officecashbox'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officekassaincome',
            name='office_cashbox',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='office_cashbox_income', to='cashbox.officecashbox'),
            preserve_default=False,
        ),
    ]
