# Generated by Django 4.0.7 on 2022-08-28 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.company')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='company.office')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_warehouse', 'Mövcud anbarlara baxa bilər'), ('add_warehouse', 'Anbar əlavə edə bilər'), ('change_warehouse', 'Anbar məlumatlarını yeniləyə bilər'), ('delete_warehouse', 'Anbar silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_and_quantity', models.CharField(blank=True, max_length=250, null=True)),
                ('note', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('employee_who_sent_the_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_requests', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_note', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('view_warehouserequest', 'Mövcud anbar sorğularına baxa bilər'), ('add_warehouserequest', 'Anbar sorğu əlavə edə bilər'), ('change_warehouserequest', 'Anbar sorğu məlumatlarını yeniləyə bilər'), ('delete_warehouserequest', 'Anbar sorğu silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_stock', 'Mövcud stoklara baxa bilər'), ('add_stock', 'Stok əlavə edə bilər'), ('change_stock', 'Stok məlumatlarını yeniləyə bilər'), ('delete_stock', 'Stok silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_and_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('operation_date', models.DateField(auto_now_add=True, null=True)),
                ('operation_type', models.CharField(choices=[('transfer', 'transfer'), ('stok yeniləmə', 'stok yeniləmə')], default='transfer', max_length=50)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL)),
                ('receiving_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_warehouse', to='warehouse.warehouse')),
                ('shipping_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_warehouse', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ('pk',),
                'permissions': (('view_operation', 'Mövcud əməliyyatlara baxa bilər'), ('add_operation', 'Əməliyyat əlavə edə bilər'), ('change_operation', 'Əməliyyat məlumatlarını yeniləyə bilər'), ('delete_operation', 'Əməliyyat silə bilər')),
                'default_permissions': [],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique name for your constraint'),
        ),
    ]
